AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-example

  Sample SAM Template for sam-example

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  QuarkusLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/quarkus-lambda-1.0-SNAPSHOT-runner.jar
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: post
      Policies: AWSLambdaBasicExecutionRole

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  QuarkusLambdaFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt QuarkusLambdaFunction.Arn
  QuarkusLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt QuarkusLambdaFunction.Arn

#  AWSTemplateFormatVersion: '2010-09-09'
#  Transform: AWS::Serverless-2016-10-31
#  Description: AWS Serverless Quarkus HTTP - com.example::quarkus-lambda
#  Globals:
#    Api:
#      EndpointConfiguration: REGIONAL
#      BinaryMediaTypes:
#        - "*/*"
#
#  Resources:
#    QuarkusLambdaFunction:
#      Type: AWS::Serverless::Function
#      Properties:
#        Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
#        Runtime: java8
#        CodeUri: target/quarkus-lambda-1.0-SNAPSHOT-runner.jar
#        MemorySize: 128
#        Timeout: 15
#        Policies: AWSLambdaBasicExecutionRole